{% set name = "fastparquet" %}
{% set version = "2025.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/{{ name }}/{{ name }}-{{ version  }}.tar.gz
  sha256: 85f807d3846c7691855a68ed7ff6ee40654b72b997f5b1199e6310a1e19d1cd5

build:
  number: 0
  # skip s390x because of lack of cramjam and numba
  skip: true  # [py<39 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - git  # [not win]
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - numpy {{ numpy }}
    - cython >=0.29.31
    - numpy >=2.0.0rc1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas >=1.5.0
    - cramjam >=2.3
    - fsspec
    - packaging

test:
  imports:
    - fastparquet
    - fastparquet.cencoding
    - fastparquet.speedups
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dask/fastparquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python interface to the parquet format
  description: |
    The fastparquet is a python implementation of the parquet format, aiming integrate into python-based big data work-flows.
    It is used implicitly by the projects Dask, Pandas and intake-parquet.
    The Parquet format is a common binary data store, used particularly in the Hadoop/big-data sphere.
    It provides several advantages relevant to big-data processing.

  dev_url: https://github.com/dask/fastparquet
  doc_url: https://fastparquet.readthedocs.io

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
