{% set name = "fastparquet" %}
{% set version = "0.0.2" %}
{% set fn_suffix = "0.0.2.tar.gz" %}
{% set sha256 = "71a22265355ddb7335eb1ab2895b5c17e5b42bb93fe171068195e5eb02ed6c53" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ fn_suffix }}
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ fn_suffix }}
  sha256: "{{ sha256 }}"

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - numpy
    - numba
    - thriftpy
    - pytest

test:
  imports:
    - fastparquet

about:
  home: http://github.com/martindurant/fastparquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  dev_url: https://github.com/martindurant/fastparquet

extra:
  recipe-maintainers:
    - martindurant
