{% set name = "fastparquet" %}
{% set version = "2026.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # https://pypi.org/packages/source/f/fastparquet/fastparquet-2026.3.0.tar.gz doesn't exist
  url: https://github.com/dask/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 83b404a55bf579e789db79e4b948c2633a4da6dbb0b00ae56b05b75036dcf8f4

build:
  number: 0
  skip: true  # [py<310]
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    # build fails at setup.py line 47 with subprocess execution on win
    # subprocess.call(["git", "status"], stdout=sys.stdout, stderr=sys.stderr)
    - git  # [win or linux]
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - cython >=0.29.31
    - numpy {{ numpy }}
    - numpy >=2.0.0rc1
  run:
    - python
    - pandas >=1.5.0
    - numpy
    - cramjam >=2.3
    - fsspec
    - packaging
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fastparquet
    - fastparquet.cencoding
    - fastparquet.speedups
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/fastparquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python interface to the parquet format
  description: |
    The fastparquet is a python implementation of the parquet format, aiming integrate into python-based big data work-flows.
    It is used implicitly by the projects Dask, Pandas and intake-parquet.
    The Parquet format is a common binary data store, used particularly in the Hadoop/big-data sphere.
    It provides several advantages relevant to big-data processing.
  dev_url: https://github.com/dask/fastparquet
  doc_url: https://fastparquet.readthedocs.io

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
