{% set name = "fastparquet" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ version  }}.tar.gz
  sha256: 3b558059327dce2c73a775aa2f2029e052fcf6e61880e15681e04ede5f0f20b7

build:
  number: 3
  # Currently it's not available on s390x:
  # There is a missing numba package.
  skip: True  # [py<36 or s390x]
  script:
    - del fastparquet\*.c  # [win]
    - rm fastparquet/*.c   # [unix]
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython 0.29.32
    - numba 0.57.0
    - numpy {{ numpy }}
    - packaging
    - pandas
    - pip
    - pytest-runner
    - setuptools
    - thrift >=0.11
  run:
    - python
    - numba >=0.49
    - packaging
    - pandas >=1.1.0
    - {{ pin_compatible('numpy') }}
    - thrift >=0.11

test:
  imports:
    - fastparquet
  commands:
    - pip check || true    # [not win]
    - pip check || exit 0  # [win]
  requires:
    - pip

about:
  home: https://github.com/dask/fastparquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  dev_url: https://github.com/dask/fastparquet
  doc_url: https://github.com/dask/fastparquet/blob/main/docs/source/quickstart.rst

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
