{% set name = "fastparquet" %}
{% set version = "2026.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # https://pypi.org/packages/source/f/fastparquet/fastparquet-2026.3.0.tar.gz doesn't exist
  url: https://github.com/dask/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9a6fa0e1750fa77dc435415116120b5c7c9bfdec2c0b1e6d2c91bee4d5066ed5

build:
  number: 1
  # cramjam 2.12.0 doesn't support Python 310 anymore
  # https://github.com/milesgranger/cramjam/blob/3b07aadfb13ba03a0b4582f07b3fa0e1f40c94bd/pyproject.toml#L6
  skip: true  # [py<311]
  script: 
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    # build fails at setup.py line 47 with subprocess execution on win
    # subprocess.call(["git", "status"], stdout=sys.stdout, stderr=sys.stderr)
    - git  # [win or linux]
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools-scm
    - cython >=0.29.31
    - numpy {{ numpy }}
  run:
    - python
    - pandas >=1.5.0
    - numpy
    - cramjam >=2.3.0
    - fsspec
    - packaging

test:
  imports:
    - fastparquet
    - fastparquet.cencoding
    - fastparquet.speedups
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/fastparquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python interface to the parquet format
  description: |
    The fastparquet is a python implementation of the parquet format, aiming integrate into python-based big data work-flows.
    It is used implicitly by the projects Dask, Pandas and intake-parquet.
    The Parquet format is a common binary data store, used particularly in the Hadoop/big-data sphere.
    It provides several advantages relevant to big-data processing.
  dev_url: https://github.com/dask/fastparquet
  doc_url: https://fastparquet.readthedocs.io

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
