{% set name = "fastparquet" %}
{% set version = "2025.12.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version  }}.tar.gz
  sha256: 85f807d3846c7691855a68ed7ff6ee40654b72b997f5b1199e6310a1e19d1cd5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - wheel
    - setuptools
    - setuptools-scm
    - cython >=0.29.31
    - numpy {{ numpy }}
  run:
    - python
    - pandas >=1.5.0
    - numpy
    - cramjam >=2.3.0
    - fsspec
    - packaging

test:
  imports:
    - fastparquet
    - fastparquet.cencoding
    - fastparquet.speedups
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dask/fastparquet
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  description: |
    The fastparquet is a python implementation of the parquet format, aiming integrate into python-based big data work-flows.
    It is used implicitly by the projects Dask, Pandas and intake-parquet.
    The Parquet format is a common binary data store, used particularly in the Hadoop/big-data sphere.
    It provides several advantages relevant to big-data processing.
  dev_url: https://github.com/dask/fastparquet
  doc_url: https://fastparquet.readthedocs.io

extra:
  skip-lints:
    - invalid_url
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
