{% set name = "fastparquet" %}
{% set version = "0.6.3" %}
{% set sha256 = "1c2899edef45c9fb9cbb8a1dd37c5ed3878ed4d17102f0df332a9d764d28eaee" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/f/{{ name }}/{{ name }}-{{ version  }}.tar.gz
  sha256: "{{ sha256 }}"

build:
  number: 1
  script:
    - del fastparquet\*.c  # [win]
    - rm fastparquet/*.c   # [unix]
    - "{{ PYTHON }} -m pip install . --no-deps -vv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pandas
    - pip
    - setuptools
    - numpy
    - pytest-runner
    - numba
    - packaging
    - thrift 0.11
  run:
    - python
    - pandas >=0.19
    - numpy
    - packaging
    - numba >=0.28
    - thrift 0.11

test:
  imports:
    - fastparquet

about:
  home: http://github.com/dask/fastparquet
  license: BSD-3
  license_family: 'BSD'
  license_file: LICENSE
  summary: 'Python interface to the parquet format'
  dev_url: https://github.com/dask/fastparquet

extra:
  recipe-maintainers:
    - martindurant
    - mrocklin
    - TomAugspurger
