travis:
  secure:
    BINSTAR_TOKEN: W0HPntrWtPNz7OXrDqF3mnhYm9y9rZNPfHWTj+craVRFMfFuWObSu/5EMCV6Kd9Kbrf/NhBdegbMSEFQV7vW0AV6nkj3SiQgZFmTv/7yjuOJq5zU7+7khfIjm4v33hKnPwTwOcyd+vX6u/XDiTuS1S7ESnnRKzZ6Eyxdhi7TMEXsIyhdO6ZI1jzYbSbzFaKBwsEsBcLnGTMpanokeQJ1nzeY/rATQdigj+6d/4hxQvSlPyG22d6nVLndRissdx/N0008dDEHFItO5aMfE9ZS6Vrf0mgz5FaP4XcAhbdhfLhC5Igyx4Iruws8QLRvxtNBP34dppLUa37UM/KePSG8xeNGOmG0NyODlPdXvI+Ed+5YjUo0uI+g/7DCpeQm/BQY8Mtu5bs0RGMbT1usgmkHiHcxPmqX56NUh8UboWgI3vsqimvpcGZrgKjQPVjK0tH0bLIDRGF96Iw0afuTPsak9e5xs8IiMzp8oeqJoyyo97XZCbv7I/9/M5junfkdWUw7LRsz45BzyGpp2lByuMz5SE6ccXQuFP3Q5u23aKB9gz6XhF77k9J7zeJUm8+1nYSTwV1CbGMScRRnbvOiNqNPooVp6+PAkYmuihFbCMkcImqU3d5jiukGVcTLGiNrgdPF2GM1uMa7gZN2+8hpoGN/7NtzroIjimUv0E6R8g5Vk60=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
